### PR TITLE
Migrate ClientJavaE2E from Grakn Core

### PR DESCRIPTION
**Pull request by flyingsilverfin**
## What is the goal of this PR?
https://github.com/graknlabs/grakn/issues/5043 lists that we want to remove client-java-e2e from grakn core and put it in an `assembly` test in this repository. This PR migrates the test and adapts it for the repository.

## What are the changes implemented in this PR?
* Migrate test into new package `test/assembly`
* Adapt assetions and server bootup to match client-java style
* Add to CI

### CODE REVIEW

**Comment by flyingsilverfin** [comment]
@lolski you think this is a large integration test? The original issue indicates to place it into a `assembly` package but not sure that is the best place, it's really a huge integration test or sorta e2e. Assumiing `assembly` is the name of our new e2e in general!

**Comment by flyingsilverfin** [comment]
good point!

**Comment by flyingsilverfin** [comment]
Ok - the test executes a long series of Queries so I've renamed it to `QueriesTest`

**Comment by haikalpribadi** [comment]
> Ok - the test executes a long series of Queries so I've renamed it to `QueriesTest`

Possible. Let's keep it singular. "QueryTest".

**Pull request merged**
